<a href="https://colab.research.google.com/github/Mayank-Singh-X1/Pytorch-notes/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
a =torch.tensor([ [2,3,4,5], [2,3,4,5] ])
a.ndim

2

In [ ]:
a = torch.rand(size = (3,4))
a, a.dtype

(tensor([[0.9738, 0.7301, 0.8389, 0.6965],
         [0.9304, 0.8727, 0.7500, 0.1548],
         [0.5612, 0.7408, 0.3697, 0.4018]]),
 torch.float32)

In [ ]:
ab = torch.rand(size = (1,3))
print(ab)
c = ab -1
print(c)
ab.shape
ab.ndim

tensor([[0.4918, 0.9426, 0.9906]])
tensor([[-0.5082, -0.0574, -0.0094]])


2

In [ ]:
a= torch.tensor([1,3,2])
b= torch.tensor([1,2,3])
# torch.matmul(a,b)
print(a@b)
print(a.ndim)
print(b.ndim)

tensor(13)
1
1


In [ ]:
a= torch.arange(1,10)
a.shape
a.reshape(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=2 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.6147, 0.3810, 0.6371, 0.4745],
        [0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332]])

Tensor D:
tensor([[0.6147, 0.3810, 0.6371, 0.4745],
        [0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
!nvidia-smi

Tue Jul  7 12:58:37 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   60C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
torch.cuda.is_available()

True